server:
  port: 1011

spring:
  application:
    name: IDEAL-SYN

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
    # 是否注册自身到eureka服务器
    register-with-eureka: true
    fetch-registry: true