server:
  port: 1010

spring:
  application:
    name: IDEAL-RABBITMQ
#  rabbitmq:
#    host:
#    username: "guest"
#    password: "guest"
#    port: 5672
#    addresses:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
    # 是否注册自身到eureka服务器
    register-with-eureka: true
    fetch-registry: true