server:
  port: 1010

spring:
  application:
    name: IDEAL-RABBITMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /smsAndEmail
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5 # 最大重试次数
          initial-interval: 1000ms # 第一次和第二次之间的重试间隔，后面的用乘子计算
          multiplier: 2 # 乘子
          max-interval: 3600000ms #最大重试间隔时间

eureka:
  instance:
    hostname: rabbit-service
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
    # 是否注册自身到eureka服务器
    register-with-eureka: true
    fetch-registry: true