server:
  port: 1002

spring:
  application:
    name: IDEAL-GATEWAY
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
      # 路由标识（id：标识，具有唯一性）   简单尝试
      - id: route_simple
        # 目标服务地址（uri：地址，请求转发后的地址）
        uri: https://www.zouwencong.com
        # 路由条件（predicates：断言，匹配 HTTP 请求内容）
        predicates:
        ## 转发地址格式为 uri/archive
        - Path=/archive
      # --------------------- SPRINGLEARN 模块路由--------------------- #
#      - uri: lb://IDEAL-SPRINGLEARN
#        predicates:
#          - Path=/ysl/gateway/test/**
#        filters:
#          - StripPrefix=3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
    # 是否注册自身到eureka服务器
    register-with-eureka: true
    fetch-registry: true
