server:
  port: 1002

spring:
  application:
    name: IDEAL-GATEWAY
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
      # --------------------- SPRINGLEARN 模块路由--------------------- #
      - uri: lb://IDEAL-SPRINGLEARN
        predicates:
          - Path=/ysl/gateway/test/**
        filters:
          - StripPrefix=3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
    # 是否注册自身到eureka服务器
    register-with-eureka: true
    fetch-registry: true
