server:
  port: 1002
spring:
  application:
    name: IDEAL-GATEWAY
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: springlearn
          # eureka 好像注册有问题，服务通过网关访问
#          uri: lb://IDEAL-SPRINGLEARN
          uri: http://127.0.0.1:1015
          predicates:
            - Path=/ysl/gateway/**
          filters:
            - StripPrefix=2


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
    # 是否注册自身到eureka服务器:true-注册  false:不注册
    register-with-eureka: true
    fetch-registry: true